import Config

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

config :bighead, Bighead.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "bighead_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  pool_size: 10

config :bighead, BigheadWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cn/O2NwxTOW1Y1C9xd6Y/Pcb7yu1qpkfo/XwsNoCDUhr+HkCBZhpFBcIFuPCvOg0",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:bighead, ~w(--sourcemap=inline --watch)]},
    # Print the telemetry metrics defined in `BigheadWeb.Telemetry.metrics/0` to the
    # console. None of the bighead events fire yet — this is here so that the ones
    # added from Phase 3 onward are visible without further wiring.
    tailwind: {Tailwind, :install_and_run, [:bighead, ~w(--watch)]}
  ]

config :bighead, :telemetry_console_reporter, false

# Enable dev routes for dashboard and mailbox
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
config :bighead, dev_routes: true

# Deliberately empty, overriding `config/config.exs`: in dev you want to read
# the hook payloads. Nowhere else.
config :phoenix, :filter_parameters, []

# Initialize plugs at runtime for faster development compilation
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#
# in production as building large stacktraces may be expensive.
# The `http:` config above can be replaced with:
#
# ## SSL Support
#     https: [
#

config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  #       port: 4001,
  # Changing this configuration will require mix clean and a full recompile.
  #       cipher_suite: :strong,
  #       keyfile: "priv/cert/selfsigned_key.pem",
  #       certfile: "priv/cert/selfsigned.pem"
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  #     ],
  #
  # If desired, both `http:` and `https:` keys can be
  # configured to run both http and https servers on
  enable_expensive_runtime_checks: true

config :swoosh, :api_client, false

# Disable swoosh api client as it is only required for production adapters.
# different ports.
