import Config

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Configure your database
# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :mem0, Mem0.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "mem0_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  pool_size: 10

config :mem0, Mem0Web.Endpoint,
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cn/O2NwxTOW1Y1C9xd6Y/Pcb7yu1qpkfo/XwsNoCDUhr+HkCBZhpFBcIFuPCvOg0",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:mem0, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:mem0, ~w(--watch)]}
  ]

# Print the telemetry metrics defined in `Mem0Web.Telemetry.metrics/0` to the
# console. None of the mem0 events fire yet — this is here so that the ones
# added from Phase 3 onward are visible without further wiring.
config :mem0, :telemetry_console_reporter, false

# ## SSL Support
#

# Enable dev routes for dashboard and mailbox
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
config :mem0, dev_routes: true

# Initialize plugs at runtime for faster development compilation
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#
# in production as building large stacktraces may be expensive.
# The `http:` config above can be replaced with:
#
#     https: [
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  #       port: 4001,
  # Changing this configuration will require mix clean and a full recompile.
  #       cipher_suite: :strong,
  #       keyfile: "priv/cert/selfsigned_key.pem",
  #       certfile: "priv/cert/selfsigned.pem"
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  #     ],
  #
  # If desired, both `http:` and `https:` keys can be
  # configured to run both http and https servers on
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
# different ports.

config :swoosh, :api_client, false
